DROP TABLE IF EXISTS TBL_CUSTOMER;
CREATE TABLE TBL_CUSTOMER (
  CID INT PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL
);

DROP TABLE IF EXISTS TBL_ACCOUNTS;
CREATE TABLE TBL_ACCOUNTS (
  ACCOUNT_NUMBER VARCHAR(20) PRIMARY KEY,
  CARD_NUMBER VARCHAR(20) UNIQUE NOT NULL,
  BALANCE DECIMAL(16,3) NOT NULL,
  CID INT NOT NULL
);
